name: Add Issue

on:
  workflow_dispatch
  
jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat ISSUES_TEMPLATE/tsv-validation-failed.md >> $GITHUB_EVENT_PATH

